apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessus
  labels:
    app: nessus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessus
  template:
    metadata:
      labels:
        app: nessus
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nessus
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "nessus"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      securityContext:
        runAsUser: 0  # Ensures the pod runs as a non-root user
        fsGroup: 0    # Ensures the volume is mounted with appropriate group permissions
      containers:
        - name: nessus
          image: tenable/nessus:latest-ubuntu  # Replace with the correct Nessus image reference
          ports:
            - containerPort: 8834  # Nessus web interface port
          securityContext:
            capabilities:
              add:
                - NET_RAW

