apiVersion: v1
kind: Service
metadata:
  name: nessus-nodeport-service  # Nom unique pour le service NodePort
spec:
  selector:
    app: nessus
  ports:
  - protocol: TCP
    port: 8834
    targetPort: 8834
    nodePort: 32002  # Port NodePort, choisissez un port disponible
  type: NodePort
