apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.17.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
